### ISSUE TITLE
Invite more users into the Tracker tool.

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3268]
The goal is to invite more members of the community to use Tracker.

- [ ] High-level invitation (Po)
- [ ] User-level invitations
- [ ] Secure GC Digital Community of Practice (COP)
- [ ] UX Suggestion on improvements
