### ISSUE TITLE
Tracker Website Redesign

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3450]
- [x] Test design from a Dev implementation standpoint
- [x] Present new design - Bryon (work with Jason) to create deck with screenshots.  Presenting to Rahim and Po.
- [x] Design signoff
- [x] Implementation
- [x] SVG version of the Logo****
- [x] Colour details
