### ISSUE TITLE
Update Tracker Documentation

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3514]
Update `README.md` files and [GitHub Wiki](https://github.com/canada-ca/tracker/wiki) to reflect modern architecture and features of Tracker, including:
- [ ] Background/Purpose/Requirements
- [ ] Guidance Tags
- [ ] Full stack architecture
- [ ] API How-to (Apollo Studio self-documenting queries/mutations)
- [ ] Auth role structure
- [ ] Scanners
- [ ] Integration with 3rd party apps
- [ ] Code/Contribution conventions
- [ ] Main Features
