### ISSUE TITLE
Tracker 3.0 (brain storing session info, all moved to new tickets).

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3531]
Target Q4 2022/23
Critical path:  Q3 2022/23

**Needed for Tracker 3.0**
- [x] Web checks (Work breakdown items)
- [x] Break down top 2021 CVE into smaller chunks (new) (Already in the backlog)
- [x] Get insider details on NCSC Web Checks (was action item - Rahim has contacts)
- [x] A/B testing strategy (new)
- [x] The ability to hide domains (from scans without removing the domain from Tracker)(The ability to 'check a box' on a domain to include/exclude that domain from the scan) https://github.com/canada-ca/tracker/issues/3505
- [x] Wire framing
- [x] SA&A update (new)

**Nice to have for Tracker 3.0**
- [x] Self-service model  'No human contact'
- Password resets (example)
- [x] Reporting (DMARC already exists.) Low effort to include domains.
- [x] Historical line graph view/bar graph view (dependant on historical data yet to be built)
- [x] Working-level enhancements (Create process to include ideas/suggestions from the user community)
- [x] Exec-level enhancements
- [x] Feedback loop
- [x] How to invite Admins (how many per organization?)
- [x] How to assign admins to organization.
- [x] Provide actionable advise to users/admins and execs
- [x] Identify and understand adjacent tools that are used in conjunction with Tracker

**Not Needed for Tracker 3.0**
- [x] Link code to policy
- [x] Meet with front-line organizations to learn current landscape
- [x] Community feedback to improve Tracker (users/provinces)

Reference material:
- https://github.com/ukncsc/SME/blob/main/ncsc-scanning-made-easy-script-developer-guidelines.md
- https://www.cisa.gov/known-exploited-vulnerabilities-catalog
- https://www.cisa.gov/cyber-hygiene-services#:~:text=Cyber%20Hygiene%20services%20are%20provided,government%20and%20critical%20infrastructure%20stakeholders.
