### ISSUE TITLE
Tracker website Prioritization

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3534]
Notes from March 16 discussion:

- [x] Develop Admin flow (sign-in and log-in)  
- [x] Export flows via PDF - Action Luke
- [x] if you are an Org. Admin, click here.  (create a domain) (Not required:  Jason)
- [x] Jason to design navigation collapse.  (Not required:  Jason)
- [x] Jason to text consistency across the browser design.  Action:  Jason
- [x] Glossary button to the bottom (overlay)  Action:  Luke
- [x] Jason to provide button state values (Over, down, etc.) Action:  Jason
- [x] Add a 'back button' to domain list detail.  Action:  Luke
- [x] Add link to main logo - to return to the main page.  Action:  Luke 
- [x] Spinning "system working" notification colour - currently grey, add colour.  (Jason to provide colour values)  Action:  Jason
- [x] Remove black sidebar - (dependant on screen size)  Action:  Complete
- [ ] Focus on Mobile experience. (Low priority for now)
- [x] Add Guidance Page link to footer. 
- [x] In Web Guidance - Change SSL to TLS

- [ ] For discussion - Adding more tabs to the results (IP address tab)
