### ISSUE TITLE
Update Tracker Documentation

### ISSUE THREAD

**Issue by CADbryon** [canada-ca/tracker#3863]
Update Tracker guidance.

### Must have
- [x] Update guidance tags https://github.com/canada-ca/tracker/wiki/Guidance-Tags
- [x] [Tracker Guidance 2.1 update] (sent for translation)(https://056gc.sharepoint.com/sites/OCIOCyberSecurity/Shared%20Documents/General/09.%20Cyber%20Tools/Tracker/Tracker%20Guidance%202.1%20update%20-%20sent%20to%20translation%20v3.docx?web=1)
- [x] Remove all references of Information Technology Policy Implementation Notice (ITPIN), replace with Appendix G: Standard on Enterprise IT Service Common Configuration
- [x] Remove ITPIN reference https://tracker.canada.ca/contact-us
- [x] Improve contact page. https://github.com/canada-ca/tracker/wiki/Contact

**THE BELOW HAS BEEN MOVED INTO A NEW TICKET.**

### Nice to have
- [ ] Perform a ROT analysis when possible. Redundant, Outdated, Trivial. Anything that relevant should be flagged to be removed.
- [ ] Info about rules and guidance.
- [ ] Info about parked domains
- [ ] Fix any 404s (on GitHub wiki)

- [ ] Update numbers in domain section - https://github.com/canada-ca/tracker/wiki/Comparing-Results-from-Tracker-1.0-and-Tracker-2.0#domains
- [ ] Create  (OR DONT) https://github.com/canada-ca/tracker/wiki/Comparing-Results-from-Tracker-3.0-and-Tracker-2.0
- [ ] Update tech pages https://github.com/canada-ca/tracker/wiki/Component-Overview

- [ ] Review for any Tracker updates related to the Sept 2022 re-release of https://cyber.gc.ca/en/guidance/cryptographic-algorithms-unclassified-protected-protected-b-information-itsp40111
- [ ] Sunset https://wiki.gccollab.ca/GC_HTTPS_Everywhere
- [ ] Sunset https://www.gcpedia.gc.ca/wiki/HTTPS_Initiative
- [ ] GitHub wiki pages - "Home" is missing screenshot "This is what it looks like with demo data: Landing page - demo data"
- [ ] Sunset https://pulse.alpha.canada.ca/
- [ ] Customized GitHub default branch is named 'main'.

**Comment by h701h** [comment]
Process to update Guidance
0. update guidance, https://github.com/canada-ca/tracker/wiki/Guidance-Tags
1. create a branch called update-ssl#-guidance
2. update English guidance
3. update English description for link
4. update English link 
5. erase french guidance
6. erase french description for link
7. update french link
8. commit some changes
9. send copy of new English guidance to french translator (see below) 
10. wait for french translation
11. paste french into branch called update-ssl#-guidance. 
12. pull request. 


Golden, Nathan <Nathan.Golden@tbs-sct.gc.ca> 
Subject: Translation request of less than 50 words (ssl1)
Body:
 

Hello Nathan, 

Please translate the following:

"Government of Canada domains are subject to TBS website and service hardening requirements"


Thank you, 

<add your signature>
