### ISSUE TITLE
Develop a SLA understanding for the Tracker team

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#3878]
- [x] Meeting set
- [x] Monitoring inbox process
- [x] 6 - 8 hour acknowledgement time
- [x] Also, Sunset Tracker in the IMTD Azure environment?
- [ ] tracker@tbs-sct.gc.ca
