### ISSUE TITLE
Update tracker.canada.ca/guidance

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#4004]
https://github.com/canada-ca/tracker/edit/master/services/guidance/guidance.json

- [x] [French Content](https://056gc.sharepoint.com/sites/OCIOCyberSecurity/Shared%20Documents/General/09.%20Cyber%20Tools/Tracker/French%20Translations/FINAL-7162321_1-FR-REV-NG%20(002).docx?web=1)

- [x] [English Content ](https://056gc.sharepoint.com/sites/OCIOCyberSecurity/Shared%20Documents/General/09.%20Cyber%20Tools/Tracker/Tracker%20Guidance%202.1%20update%20-%20sent%20to%20translation%20v3.docx?web=1)

- [x] Remove ITPIN icon from /domains

- [ ] In review
