### ISSUE TITLE
Deal with WWW problem that is confusing Tracker users

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#4051]
Currently "www" is being appended to domains when being scanned, but the frontend results show the domain results as if there was no "www" appended to the scanned domain. This is confusing users as they work to achieve compliance with the requirements.

The way forward will be discussed at stand up on Monday October 17th. 

For example, the results for "www.dsc-sdc.gc.ca" are the results being shown below. But to the end user it appears the results are from "dsc-sdc.gc.ca"

![Image](https://user-images.githubusercontent.com/74711155/195892427-48a56198-36df-4a80-b0bd-1fb853c006ef.png)

- [x] Banner in guidance section
- [x] Banner in domain section
- [ ] Add banner to domain list of org view (https://tracker.canada.ca/organizations/natural-resources-canada/domains)
- [x] English banner text
- [x] French banner text

ENGLISH:
Tracker HSTS and HTTPS results display incorrectly when a domain has a non-compliant WWW subdomain. Check your WWW subdomain if your results appear incorrect. For example, the results for www.canada.ca in the Tracker platform are included in the results for canada.ca. Work is in progress to separate the results.”

FRENCH: 
Les résultats de suivi des domaines HSTS et HTTPS s’affichent incorrectement lorsqu’un domaine possède un sous-domaine WWW qui ne se conforme pas aux règles. Vérifiez votre sous-domaine WWW si vos résultats vous semblent incorrects. Par exemple, les résultats que l’on obtient pour le site www.canada.ca dans la plateforme de suivi sont inclus dans les résultats pour le site canada.ca. Les travaux sont en cours pour séparer les résultats.
