### ISSUE TITLE
Remove old Tracker domains

### ISSUE THREAD

**Issue by h701h** [canada-ca/tracker#4147]
Remove the following domains from existence. 
- [x] pulse.alpha.canada.ca
- [x] https-everywhere.canada.ca
- [x] https-partout.canada.ca

**Comment by FestiveKyle** [comment]
PR and linked issue for pulse.alpha.canada.ca removal: https://github.com/cds-snc/dns/pull/295

**Comment by FestiveKyle** [comment]
PR merged, getting `NXDOMAIN` status when querying for pulse.alpha.canada.ca
