### ISSUE TITLE
Create asset states for internal use by organizations

### ISSUE THREAD

**Issue by lcampbell2** [canada-ca/tracker#5536]
Align Tracker states with ASM states. For example, dependency https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/external-attack-surface-management/what-is-discovery.md#confirmed-inventory-vs-candidate-assets

**Stage 1:**
- [x] allow admins to assign and update states to their domains
- [x] create wording to explain different states
- [x] display state on domain cards

**Stage 2:**
- [x] allow filtering by asset states
- [x] deprecate/remove current methods of labelling assets as hidden or outside scope

**Stage 3:**
- [x] decide which asset states get used in summary calculations

**Other**

- [ ] Sync asset state changes with ASM tooling
